[build]
builder = "nixpacks"

[deploy]
startCommand = "./startup.sh"
healthcheckPath = "/health"
healthcheckTimeout = 10

[deploy.envs]
PYTHONUNBUFFERED = "1"

[[mounts]]
source = "data"
destination = "/app/data"
